replicaCount: 2

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: juice-shop-prod
    alb.ingress.kubernetes.io/tags: Environment=prod